site_name: DAW-MP6 Des. Web Entorn Client (Front-End)

theme:
  name: material
  features:
    - navigation.footer
    - toc.integrate
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: ca
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: light green
      accent: tale
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: light green
      accent: light green

plugins:
  - social
  - search

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/prosfp/DAW_MP06
    - icon: fontawesome/brands/creative-commons
      link: https://creativecommons.org/licenses/by-nc-sa/4.0/

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format:
            !!python/name:pymdownx.superfences.fence_code_format # Page tree


nav:
  - Inici: index.md
  - UF 1 Sintaxi i objectes predefinits del llenguatge:
      - Selecció d'arquitectures i eines de programació: UF1/UF1.1/UF1.1.md
      - Aplicació i verificació de la sintaxi del llenguatge:
          - Introducció a JS: UF1/UF1.2/UF1.2.1_IntroJS.md
          - Comentaris, tipus de dades, constants i variables: UF1/UF1.2/UF1.2.2_Variables.md
          - Operadors: UF1/UF1.2/UF1.2.2b_Operadors.md
          - Sentencies i estructures de control:
              - Estructures condicionals: UF1/UF1.2/UF1.2.3_Condicionals.md
              - Estructures repetitives: UF1/UF1.2/UF1.2.4_Bucles.md
          - Scope: UF1/UF1.2/UF1.2.5_Scope.md
      - Identificació i aplicació dels objectes predefinits del llenguatge:
          - Objectes propis de JS: UF1/UF1.3/UF1.3_Objectes_predefinits.md
          - Number: UF1/UF1.3/UF1.3.1_Number.md
          - String: UF1/UF1.3/UF1.3.2_String.md
          - Date: UF1/UF1.3/UF1.3.3_Date.md
          - Math: UF1/UF1.3/UF1.3.4_Math.md
          - RegExp: UF1/UF1.3/UF1.3.5_RegExp.md
          - JSON: UF1/UF1.3/UF1.3.6_JSON.md
      - Recursos addicionals: UF1/UF1_recursos.md
  - UF 2 Programació amb llistes, objectes i funcions definides per l’usuari:
      - Funcions: UF2/UF2.1/UF2.1.1_Funcions.md
      - Objectes: UF2/UF2.1/UF2.1.2_Objectes.md
  - Tooling:
      - VSCode: Tooling/vscode.md
      - Git & Github: Tooling/github.md

copyright: 2023 Pablo Ros
