site_name: DAW-MP6 Des. Web Entorn Client (Front-End)

theme:
  name: material
  features:
    - navigation.footer
    - toc.integrate
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: ca
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: light green
      accent: tale
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: light green
      accent: light green

plugins:
  - social
  - search
  

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/prosfp/DAW_MP06
    - icon: fontawesome/brands/creative-commons
      link: https://creativecommons.org/licenses/by-nc-sa/4.0/



markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
        alternate_style: true 
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        
      
      
# Page tree
nav:
  - Inici: index.md
  - UF 1 Sintaxi i objectes predefinits del llenguatge:
      - Selecció d'arquitectures i eines de programació: UF1/UF1.1/UF1.1.md
      - Aplicació i verificació de la sintaxi del llenguatge: 
        - Introducció a JS: UF1/UF1.2/UF1.2_a.md
        - Tipus de dades i manipulació: UF1/UF1.2/UF1.2_b.md
      - Identificació i aplicació dels objectes predefinits del llenguatge: UF1/UF1.3.md
      - Recursos addicionals de JS: UF1/UF1_recursos.md

copyright: 2023 Pablo Ros
